### ISSUE TITLE
Unified Rate Limiting for Multiple Model Versions

### ISSUE THREAD

**Issue by hominsu** [yym68686/uni-api#39]
Thank you for the excellent work.

I would like to know if it's possible to set a unified rate limit across multiple versions of a model.

Specially, I have a rate limit of 1000 rpm for the `gemini-1.5-pro` model, and I aim to `gemini-1.5-pro-001`, `gemini-1.5-pro-002`, `gemini-1.5-pro`, and `gemini-1.5-pro-latest` under a single rate limit.

Would the following syntax be a viable solution?

```yaml
api_key_rate_limit:
  "gemini-1.5-pro-latest,gemini-1.5-pro,gemini-1.5-pro-001,gemini-1.5-pro-002": 1000/min
```

**Comment by yym68686** [comment]
Hello, your syntax is invalid. The correct syntax is as follows:

```yaml
api_key_rate_limit:
  gemini-1.5-pro: 1000/min
```

This will match all models containing the string gemini-1.5-pro. The rate limit for the four models gemini-1.5-pro-latest, gemini-1.5-pro, gemini-1.5-pro-001, and gemini-1.5-pro-002 will all be set to 1000/min.

The logic for configuring the api_key_rate_limit field is as follows. This is a sample configuration file:

```yaml
api_key_rate_limit:
  gemini-1.5-pro: 1000/min
  gemini-1.5-pro-002: 500/min
```

Now, if there is a request using the model gemini-1.5-pro-002.

First, uni-api will try to exactly match the model in api_key_rate_limit. If the rate limit for gemini-1.5-pro-002 is set, then the rate limit for gemini-1.5-pro-002 will be 500/min. If the requested model is not gemini-1.5-pro-002 but gemini-1.5-pro-latest, since api_key_rate_limit does not have a rate limit set for gemini-1.5-pro-latest, it will look for any model with the same prefix as gemini-1.5-pro-latest that has been set. Therefore, the rate limit for gemini-1.5-pro-latest will be set to 1000/min.
